{
 "title": "CLAS Movies Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "User BugGenerator Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "user_bugGenerator_time_seconds_count{class=\"ro.unibuc.hello.controller.UserController\",exception=\"IllegalArgumentException\",method=\"buggedInsertUser\",}"
    }
   ]
  },
  {
   "title": "/user/insert Query Failure Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "user_insertUser_count_total{class=\"ro.unibuc.hello.controller.UserController\",exception=\"IllegalArgumentException\",method=\"insertUser\",result=\"failure\",}"
    }
   ]
  },
  {
   "title": "/user/insert Query Success Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "user_insertUser_count_total{class=\"ro.unibuc.hello.controller.UserController\",exception=\"none\",method=\"insertUser\",result=\"success\",}"
    }
   ]
  },
  {
   "title": "/movie/getAll Query Time Seconds Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "movie_getMovies_time_seconds_sum{class=\"ro.unibuc.hello.controller.MovieController\",exception=\"none\",method=\"getMovies\",}"
    }
   ]
  },
  {
   "title": "/movie/getAll Query Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "movie_getMovies_time_seconds_count{class=\"ro.unibuc.hello.controller.MovieController\",exception=\"none\",method=\"getMovies\",}"
    }
   ]
  },
  {
   "title": "/review/update Query  Success Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "review_updateReview_count_total{class=\"ro.unibuc.hello.controller.ReviewController\",exception=\"none\",method=\"updateReview\",result=\"success\",}"
    }
   ]
  }
 ]
}