version: '3.1'

networks:
  default:
    external: true
    name: dev
    driver: bridge
      
services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090 
      
  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000  
