version: '3.1'

networks:
  default:
    external: true
    name: dev
    driver: bridge
      
services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090 
      
  alertmanager:
      image: prom/alertmanager:v0.12.0
      ports:
        - 9093:9093
      volumes:
        - ./prometheus/:/etc/prometheus/
      restart: always
      command:
        - '-config.file=/etc/prometheus/prometheus-alert-manager.yml'
        - '-storage.path=/prometheus'
      deploy:
        mode: global    
  
  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000  
